---
version: "2.1"
services:
  fr24front:
    image: nginx:stable-alpine3.17
    container_name: fr24front
    restart: unless-stopped
    volumes:
      - ./frontend/html/:/usr/share/nginx/html:ro
      #- ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 3145:80
    depends_on:
      - fr24back


  fr24back:
    image: node:21.5.0-alpine3.19
    container_name: fr24back
    restart: unless-stopped
    user: "node"
    working_dir: /usr/src/app
    volumes:
      - ./backend/server/:/usr/src/app:ro
    command: node server.js
    ports:
      - 3000